# Generated by Django 3.2.6 on 2021-08-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_auto_20210823_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='reporter',
            new_name='publishedat',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='headline',
            new_name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
